In [1]:
from keras.models import load_model

model = load_model('./model/model11_2.hdf5')

Using TensorFlow backend.
C:\Users\shbk0\AppData\Local\conda\conda\envs\tutorial\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


In [2]:
import pickle

#loading
with open('tokenizer.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

In [11]:
import pandas as pd
import matplotlib.pyplot as plt

df1 = pd.read_csv('../dataset/train_SectionDataset.csv', delimiter=",", header=0)
data = pd.read_csv('../dataset/test_SectionDataset.csv', delimiter=",", header=0)

data_input = data.loc[[125], :]

print(data_input)

                                  title  section
125  임혜숙 장관 후보자 디지털 뉴딜 성공으로 대한민국 대전환 기여        3


In [12]:
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.preprocessing import sequence
from keras.utils import np_utils

data_input_title = data_input.title.values
data_input_section = data_input.section.values
data_input_index = data_input.index

x = tokenizer.texts_to_sequences(data_input_title)
padded_x = sequence.pad_sequences(x, maxlen=18)
Y_prediction = model.predict(padded_x)

n = np.argmax(Y_prediction)
print('Index: ' + str(data_input_index[0]) + ', Actual Section: ' + str(data_input_section[0]) + ', Expected Section: ' + str(n))
print(data_input_title[0])

Index: 125, Actual Section: 3, Expected Section: 3
임혜숙 장관 후보자 디지털 뉴딜 성공으로 대한민국 대전환 기여


In [6]:
print(padded_x[0])

[    0     0     0     0     0     0     0     0     0  1958    40   739
   162  7282 23248   315  3504  3356]


In [7]:
print(padded_x)

[[    0     0     0     0     0     0     0     0     0  1958    40   739
    162  7282 23248   315  3504  3356]]


In [5]:
df2 = pd.concat([df1, data_input], ignore_index=True)
df3 = df2[ df2['section'] == data_input_section[0]]

print(df3)
print(df3.loc[[4855], :])

#x = []
#for i in range(0, 2501):
#    x.append(i)
    
#df3["number"] = x

print(df3)

                                             title  section
3                온더 이더리움 레이어2 솔루션 토카막 네트워크 개발자에 공개        3
7                   2022년 발사 예정인 달 탐사 궤도선 비행 방식 변경        3
11                     카카오톡 새해부터 먹통 트래픽 폭증… 2시간 장애        3
15     MS 14일부터 ‘윈도7’ 기술 지원 중단… 과기부 종합상황실 설치 보안 대응        3
19                       삼성전자 TV도 美 ‘8K UHD’ 인증 획득        3
...                                            ...      ...
9987                제주도 올해 LNG보급·탄소없는 섬 추진에 3천억 투입        3
9991             KT스카이라이프 보좌관 제작 스튜디오앤뉴 지분 9.9% 취득        3
9995                      게시판 중기중앙회 홈페이지 이용자 중심 개편        3
9999          SK텔레콤 CES 2020서 5G 기반 미디어·모빌리티 시대 연다        3
10000           임혜숙 장관 후보자 디지털 뉴딜 성공으로 대한민국 대전환 기여        3

[2501 rows x 2 columns]
                           title  section
4855  박영선 디지털 대전환 위한 관점의 이동 필요종합        3
                                             title  section
3                온더 이더리움 레이어2 솔루션 토카막 네트워크 개발자에 공개        3
7                   2022년 발사 예정인 달 탐사 궤도선 비행 방식 변경 

In [ ]:
df2 = df1[ df1['section'] == data_input_section[0]]
df3 = pd.concat([df2, data_input], ignore_index=True)
#df2.loc[0] = [data_input_title[0], data_input_section[0]]
#df3 = df2.sort_index()

#df2.loc[0] = [data_input_title[0], data_input_section[0]]

print( df3.shape )
print( df3[['title', 'section']][:3]  )

print(df3)


In [6]:
from sklearn.feature_extraction.text import CountVectorizer

print( df3[['title']].head(3) )
count_vector = CountVectorizer( ngram_range=(1,3) )
c_vector_genres = count_vector.fit_transform( df3['title'] )
print( c_vector_genres.shape )
print( c_vector_genres )

                                title
3   온더 이더리움 레이어2 솔루션 토카막 네트워크 개발자에 공개
7      2022년 발사 예정인 달 탐사 궤도선 비행 방식 변경
11        카카오톡 새해부터 먹통 트래픽 폭증… 2시간 장애
(2501, 29774)
  (0, 20397)	1
  (0, 21813)	1
  (0, 11504)	1
  (0, 16984)	1
  (0, 27063)	1
  (0, 9402)	1
  (0, 5959)	1
  (0, 7096)	1
  (0, 20398)	1
  (0, 21814)	1
  (0, 11505)	1
  (0, 16995)	1
  (0, 27064)	1
  (0, 9403)	1
  (0, 5960)	1
  (0, 20399)	1
  (0, 21815)	1
  (0, 11506)	1
  (0, 16996)	1
  (0, 27065)	1
  (0, 9404)	1
  (1, 1157)	1
  (1, 13383)	1
  (1, 20209)	1
  (1, 26936)	1
  :	:
  (2499, 12515)	1
  (2500, 8692)	1
  (2500, 11145)	1
  (2500, 23084)	1
  (2500, 10516)	1
  (2500, 10315)	1
  (2500, 16475)	1
  (2500, 22793)	1
  (2500, 29672)	1
  (2500, 9768)	1
  (2500, 22794)	1
  (2500, 23107)	1
  (2500, 29673)	1
  (2500, 11153)	1
  (2500, 9769)	1
  (2500, 16476)	1
  (2500, 10519)	1
  (2500, 10316)	1
  (2500, 22795)	1
  (2500, 23108)	1
  (2500, 29674)	1
  (2500, 11154)	1
  (2500, 9770)	1
  (2500, 16477)	1
  (2500, 10520)	1


In [7]:
from sklearn.metrics.pairwise import cosine_similarity

genres_c_sim = cosine_similarity( c_vector_genres )
print( genres_c_sim )

genres_c_sim = genres_c_sim.argsort()[:, ::-1]
print( genres_c_sim )

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
[[   0 2421 2269 ... 1630 1629 1250]
 [   1 2054 1721 ... 1656 1655    0]
 [   2 1071  218 ... 1663 1662    0]
 ...
 [2498  165  187 ... 1656 1655    0]
 [2499 2325 2468 ... 1585 1587    0]
 [2500 1213  929 ... 1661 1660    0]]


In [8]:
def get_recommend_movie_list(df, input_title, top=6):
    # 입력 제목 영화의 인텍스 값 추출
    target_index = df[ df['title'] == input_title].index.values

    print('??' + str(target_index ))
    

    # 코사인 유사도 중 비슷한 코사인 유사도를 가진 정보를 추출    
    sim_index1 = genres_c_sim[target_index, :top]
    print( sim_index1 )
    sim_index2 = sim_index1.reshape(-1)
    print( sim_index2 )
    # 본인 제외
    sim_index3 = sim_index2[ sim_index2 != target_index ]
    print( sim_index3 )
    
   
    # 최종 선택   
    return  df.iloc[ sim_index2 ]


new_string = data_input.title.values[0]
print(new_string)

get_recommend_movie_list( df3, new_string)

임혜숙 장관 후보자 디지털 뉴딜 성공으로 대한민국 대전환 기여
??[10000]


IndexError: index 10000 is out of bounds for axis 0 with size 2501